name: Resume API CI/CD

on:
  push:
    branches:
      - main
    paths:
      - "resume.json"               # ✅ Trigger when resume.json changes
      - "lambda_function/**"         # ✅ Trigger when Lambda function code changes

jobs:
  update_dynamodb:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Update Resume Data in DynamoDB
        run: |
          aws dynamodb put-item \
            --table-name Resume \
            --item file://resume.json \
            --region us-east-2

  deploy_infra:
    runs-on: ubuntu-latest
    needs: update_dynamodb  # ✅ Terraform runs after updating DynamoDB
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
